// <auto-generated />
namespace SBC.TimeCards.Data.Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MIG22022019001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MIG22022019001));
        
        string IMigrationMetadata.Id
        {
            get { return "201902230030498_MIG-22-02-2019-001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
