// <auto-generated />
namespace SBC.TimeCards.Data.Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixticket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixticket));
        
        string IMigrationMetadata.Id
        {
            get { return "201903120845344_fix-ticket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
